---
site: ld4
mgmt: 10.50.0.4/24
loop: 10.50.255.3
mc: yes
rr: no
ibgp:
  - { port: Ethernet1 }

ospf: yes

pim:
  - Ethernet1

ports:
  Ethernet1: { ip: "10.0.13.2/24", speed: 1G, desc: "vEOS-01 Uplink", ospf: yes, peer: vEOS-01 }
  Ethernet2: { ip: "", speed: 1G, desc: "vEOS-02 Uplink", ospf: no, peer: vEOS-02 }

trunks:
  Ethernet2: { native: 4094, allowed: [4094] }

mlag:
  ip: 10.0.0.2/30
  port: Ethernet2
