---
- hosts: arista
  connection: local

  vars:
   conf_dir: "{{ playbook_dir }}/configs"

  tasks:

  - name: Load service definitons
    include_vars:
     file: vlan_service.yml
     name: services

  - name: Prepare assembly dir var for host
    set_fact:
     host_tmpdir: "{{ conf_dir }}/.assembled/{{ inventory_hostname }}"
    changed_when: no

  - include_tasks: includes/validate_service_vlan.yml

  - name: CLI test
    napalm_cli:
     provider: "{{ napalm_provider }}"
     args:
      commands:
       - show vlan | json
    register: output

  - name: Load validation template
    include_vars:
     file: "{{ host_tmpdir }}/validate_service_vlan.yaml"
     name: val_file

  - name: No file
    debug:
     var: "{{ val_file }}"
     verbosity: 0

  - name: Test
    debug:
     msg: "{{ output.results | val_serv_vlan(inventory_hostname, val_file)  }}"
     verbosity: 0
